# runtime: python39

# entrypoint: gunicorn -b :$PORT finalCode:app

# handlers:
# - url: /.*
#   script: auto

# env_variables:
#   FLASK_ENV: development
runtime: python310  # or your version of Python
entrypoint: gunicorn -b :$PORT finalCode:app  # Adjust to your entry point

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  GEMINI_API_KEY: "AIzaSyCG4o9x9cm014I6bhCLjcubrtyOW0OdYwo"
